### ISSUE TITLE
Define and create new tool to generate only guidance: guidance-generate

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1012]
## Issue description / feature objectives
Users may need to handle guidance separately from the profile
A new tool is needed to do a form of guidance-generate, to split guidance off from markdown

## Completion Criteria
- [ ] Define how the tool operates and what its format is
- [ ] Implement the tool

**Comment by deenine** [comment]
I think that _guidance_ is similar to the SSP output, it has a non-editable (well ignored by `guidance-generate`) control/profile, followed by a section of editable content with a series of user-defined headers, such as 'implementation guidance' 'expected evidence' 'further guidance' 'useful links' etc. 

Thinking further, this may be exactly the same as the SSP, but outputting to multiple markdown files rather than a single markdown files. An example of 'guidance' is shown in this internal page: https://test.cloud.ibm.com/docs/ibmcloud-ciso?topic=ibmcloud-ciso-getting-started see the control families on the left hand menu bar.

An high level flow of the content that I am expecting is here:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/10449520/152413587-ff1233df-9da4-44f3-b225-0147af8f9ddb.png">

There are the following use cases for the tool:
1. As a _guidance manager_, I want to be able to create templates for my _guidance authors_ to complete, with a list of mandatory headings they should populate. 
2. As a _guidance manager_, I want to be able to assemble guidance markdown files into consumable formats, such as:
- a single MD file for conversion to PDF/DOCX
- multiple MD files for publication into an online documentation viewing system
- CSV/XLS
3. As a _guidance manager_ I want to be able to assemble guidance markdown into a computer parseable format, such as json, for import into other toolchains

**Comment by vikas-agarwal76** [comment]
So we need 2 commands -

-  _guidance-generate_ (similar to ssp-generate), which will generate guidance markdown files from resolved profile/catalog based on the guidance template. The users can then edit the markdown files to add/edit content in required / optional sections. 

-  _guidance-assemble_ command to assemble the content to a single / multiple MD files, and a json file (OSCAL profile). This command should only take the guidance sections from the MD files and rest all content is taken from the resolved catalog/profile json file. This will ensure that if a user edited any non-editable sections in markdown file then it is ignored.

Multiple MD files can be published to cloud docs and used for creating CSV/XLSX. The single MD file can be converted to PDF/DOCX.

**Comment by vikas-agarwal76** [comment]
@deenine As per your point 1 above, do we need to have a _MD template_ that can be edited by guidance manager, or a fixed set of headers that is hardcoded.

**Comment by deenine** [comment]
I am not sure that we do need to have separate commands for guidance, per my comment above, this feels very close to the activities you do for a SSP:

1. generate a bunch of templates
2. assemble the templates into oscal
3. output using a jinja template

Talking to @butler54 he thought that this could be handled as a profile, as the limitation on preventing an author editing control/profile info can be handled via an inherited profile, like the internal profile here: https://github.com/IBM/compliance-trestle-ssp-demo/blob/main/docs/information_flow.png

**Comment by deenine** [comment]
> @deenine As per your point 1 above, do we need to have a _MD template_ that can be edited by guidance manager, or a fixed set of headers that is hardcoded.

I think we need the ability to provide a list of headers that the `guidance-generate` command (or whatever we settle on as above) adds to the templates.

**Comment by vikas-agarwal76** [comment]
@deenine I think we can use the existing profile generate and assemble commands with some changes for guidance purpose. The guidance will be a new profile (importing the existing profile). In profile-generate command we will provide a new command line option to specify new guidance sections names and title. These will be added to the markdown files with empty content that can be added by the user.

Similarly, in the profile-assemble command line the same set of section names can be passed so that only those sections get added to the guidance profile json and any other sections or parameters can be ignored.

Once we have the new guidance profile json, these can either be assembled into one MD/CSV/XLSX file, converted to PDF/DOCX or published to cloud-docs.

The only thing here is if guidance owners need to change the sections (specify new one or remove existing) it has to be done via the command line (Makefile). Another way may be to capture the section names and tiles in a config/yaml file (as name value pairs) and provide that as input to the command line for specifying new sections (rather than putting the section names and titles on command line).
