### ISSUE TITLE
Add ability to generate cloud-docs

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#1013]
## Issue description / feature objectives
Currently Trestle supports the conversion of the `JSON` -> `Markdown` -> `docx`, however user might want to create a `cloud-docs` as well.

The task is to extend the existing functionality to generate cloud-docs like markdown files, add table of contents and combine everything to the cloud-docs ready format.

This will likely require the extension of the JSON to markdown conversion functionality to support multiple possible output formats, as well as writing some Jinja templates.

## Caveats / Assumptions
1. User should be able to easily change the desired docs format (IBM Cloud, Github, etc)
2. User should be able to easily include/exclude the desired sections in the markdown files

## Completion Criteria
1. User is able to generate cloud docs using Trestle.

**Comment by deenine** [comment]
I think this can be met by extending the Jinja functionality, to allow:
1. output of controls/profile/guidance/documentation as multiple MD files, rather than a single markdown file.
2. ability to select which headings should be output, for example 'implementation_guidance' and 'expected_evidence'. This is probably just something like MDSectionInclude, but indexing into the oscal not into MD files. 
3. Ability to reformat headings, probably using a simple pattern, such as `implementation_guidance` being output as `Implementation Guidance`. Alternatively just publish the block corresponding to `implementation_guidance` and let the jinja template author select the heading.

**Comment by deenine** [comment]
Further clarification:
4. Output a single md page per control, with jinja controlled formatting and content, or a md page per control, also with jinja controlled output and formatting.
5. Allow the jinja template author to specify which elements from the control they wish to present, for example control description, control guidance (from the catalog), control guidance (from the profile), control objectives, table of parameters.
