### ISSUE TITLE
Handling chaining of profiles properly

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#1187]
## Issue description / feature objectives
When multiple profiles are chained one after another, the last profile's Markdown files should show the parameters, props, and sections properly to differentiate ones that are inherited from other profile and ones that are added in the current profile.

### Sections
Sections inherited from imported profiles/catalogs should be shown before the "Editable Content" header. Any changes in these sections should be ignored.

Only sections added after the "Editable Content" header will be part of this profile.

### Parameters
x-trestle-set-params:
  ra-5_prm_1:
    profile-values: weekly operating system/infrastructure and databases; weekly container
      images; quarterly web applications; annual source code/static analysis
    values:
    display-name: RA-5 (a)

"values" will always show the inherited value from imported profiles/catalog, whereas "profile-values" will show the value set in the current profile.

### Properties
Currently we have x-trestle-add-props: only which contain the properties . We need to divide the props in YAML header into 2 groups - one inherited from imported profiles/catalogs that are only for display purpose and other for props added in the current profile.

We can retain x-trestle-add-props: to show props added in current profile and have another header like - "x-trestle-inherited-props" to show props that are inherited and cannot be updated.

Keeping the x-trestle-add-props header for props added in current profile will simplify the migration from current Markdown as inherited props are currently not shown and will be shown in a new header.

**Comment by vikas-agarwal76** [comment]
display-name property of a set-parameter should be shown even if it is inherited from imported profile or catalog.

**Comment by fsuits** [comment]
A current header looks like this:
```x-trestle-global:
  profile-title: Profile with missing reference ID
x-trestle-set-params:
  ac-1_prm_1:
    profile-values: all personnel
    values: Param_1_value_in_catalog
    display-name: AC-1
  ac-1_prm_2:
    profile-values: A thorough
    values:
  ac-1_prm_3:
    profile-values: officer
    values:
  ac-1_prm_4:
    label: organization-defined frequency
  ac-1_prm_5:
    label: organization-defined events
  ac-1_prm_6:
    label: organization-defined frequency
  ac-1_prm_7:
    label: organization-defined events
sort-id: ac-01
x-trestle-sections:
  implgdn: Implementation Guidance
  expevid: Expected Evidence
  guidance: Guidance
  sub_a: Sub A
  sub_sub_a: Sub Sub A
  sub_b: Sub B
  newguidance: New Guidance
  newevidence: New Evidence
x-trestle-add-props:
  # Add or modify control properties here
  # Properties may be at the control or part level
  # Add control level properties like this:
  #   - name: ac1_new_prop
  #     value: new property value
  #
  # Add properties to a statement part like this, where "b." is the label of the target statement part
  #   - name: ac1_new_prop
  #     value: new property value
  #     smt-part: b.
  #
  - name: ac-1_new
    value: ac-1 new value
  - name: ac1_foo
    value: ac1 bar
    ns: http://orig_ns
  - name: prop_in_expevid
    value: value in expevid
    smt-part: ac-1_expevid
  - name: ac1_a_foo
    value: ac1 a bar
    smt-part: a.
  - name: ac1_first
    value: ac1_first value
    ns: http://first
    smt-part: a.
  - name: ac-1_new_part
    value: ac-1 new part value
    smt-part: c.
  - name: cannot_add_to_resolved_cat_because_no_part_id
    value: doesnt work
    smt-part: foo_bar
```

There is a section for `x-trestle-set-params` and `x-trestle-add-props`

The `add-props` lets you add properties either to a) the control b) a top level statement part, by label such as `a.`, or to an arbitrary part by the part's name, such as `ac-1_expevid`

_In this case, `smt-part` isn't a good term because ac-1_expevid is not a statement part - it is just a part name.  So perhaps smt-part should be changed to part-name-or-smt-label_

We could add a new header section in the following way:
```
x-trestle-inherited-props:
    prop1: foo
    prop2: bar
    - name: prop_a
       value: foo
       part_name: ac-1_part
    - name: prob_b
      value: foo
      param_id: ac-1_prm_2
```
This would capture properties added or changed by upstream profiles, either via an Add or via a SetParam.  The added properties at the control level would just be shown as name/value pairs, while the properties set via setparam or by-id would be indicated as param_id or part_name.

@vikas-agarwal76 these are options to discuss

**Comment by fsuits** [comment]
After discussion:

- For inherited props, only show props from Adds in profiles - not SetParameters
- No need to add props to arbitrary parts or sections.  Only add props to top level statement parts
- Use label for statement parts, but default to using part name if label is not present
- For inherited props use consistent style with `- name:` for all, and part_name optional.  If not present, the prop is at the control level
- Keep things simple for part_name and just use name rather than a form of Display Name or label
