### ISSUE TITLE
Import and replicate needs support for optional regeneration of UUID's

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#307]
Import currently offers an option to regenerate UUID's in the imported module.  This is currently not implemented.  Similar functionality is needed for Replicate, so that same functionality should hook into Import when it is available.

**Comment by butler54** [comment]
In the oscal documents we have three scenarios
1) Declaration of uuid's as an attribute e.g. field name is 'uuid'
2) Reference to another uuid as an attribute where the name contains uuid but is not uuid.
      e.g. 'party-uuid'
      Note: we need to validate this.
3) Objects where instead of an array a key:value method where the key is a UUID.
    May contain both declarations and references and we need to validate this

Logic to regenerate UUIDs would be as follows.
1) Identify all declarations in the code according to (1) and (3)
2) Create a map of old:new uuids and update the declarations
3) Identify references to uuids and update to the new uuid using the map from step (2).
