### ISSUE TITLE
Use Trestle within a directory inside of another repository

### ISSUE THREAD

**Issue by gregelin** [IBM/compliance-trestle#474]
## Issue description / feature objectives
Objective of this feature request is to use trestle on a directory within another repository that has non-trestle related directories.

@butler54 Does trestle currently assume that trestle owns the entire git repository, or can trestle store all its content within a directory that is inside a larger directory? It's advantageous if trestle does not need to own entire repository structure.

## Completion Criteria
I can use Trestle within a repository that has non-trestle content in other directories.

## Expected Behavior
- I can tell Trestle the top directory within my repository where the trestle content should be maintained (e.g., `myrepo/some/path/trestle` or `myrepo/some/path/projects/1/trestle` plus `myrepo/some/path/projects/2/trestle`)

**Comment by fsuits** [comment]
@gregelin Currently trestle requires files to be within a valid trestle workspace in order to be manipulated, but you can import them from anywhere and have them placed into your workspace.  The trestle project workspace can be created anywhere via `trestle init` and is independent of any git repository - so there is no awareness or reliance on a git repo.  But files manipulated by trestle must reside at the appropriate place within a valid trestle project directory structure.

This is all part of the 'opinionated' aspect of trestle's operation and is similar to git.  A primary motivation is that many manipulations derive context from the location of the file in the workspace structure, so it's important for that structure to be guaranteed.

There is a somewhat related [issue]( https://app.zenhub.com/workspaces/compliance-trestle-workspace-5f597710cd0377002895a1b7/issues/ibm/compliance-trestle/359 ) to allow a `-c` option, similar to git, so that operations would proceed as if the user were temporarily at that location in the trestle workspace directory.  But the intended usage mode is for people to operate within the trestle workspace, similar to git.

In terms of your expected behavior - as long as those directory locations are valid trestle project workspaces created via `trestle init` - they should work fine already.

**Comment by butler54** [comment]
Closing as stale.
