### ISSUE TITLE
XCCDF and OPA results transformation to OSCAL findings results

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#53]
## Issue description / feature objectives
With most Cloud APIs requiring JSON as a first class citizen we need a consistent mechanism for converting 'test results' into OSCAL.

Current assumption is that asssessment-results in OSCAL is the appropriate location. The question is how to we capture 'rules' and other objects that are may or may not be 1:1 with an `objective` and represent an individual result of a technical implementation.

Usecase a: XCCDF where 1 'rule' == 1 objective.

Usecase b: NIST where N rules = 1 objective.

For this we need to test our ability to map a limited subset of 'results' formats into OSCAL finding.

1) SCAP Xccdf test results from compliance operator (or similar)[compliance_operator_AssessmentResult 7-15.json.zip](https://github.com/IBM/compliance-trestle/files/5235830/compliance_operator_AssessmentResult.7-15.json.zip)
1a) OpenSCAP xccdf results running on linux os (centos / rhel)

2) OPA inspired / generated results (https://github.ibm.com/cocoa/evidence-summary)

3) IBM S&CC results (based on spreadsheets).

## Completion Criteria
- [ ] Validate whether strict subset of OSCAL assessment results (https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/) can be used to represent the 3 cases above
- [ ] Define any expected values / conformance on top of the OSCAL schema (required / expected properties).
- [ ] Build an initial implementation which can convert xccdf from compliance operator to AR ***
- [ ] Produce a json schema based on these results.

**Comment by jeffdmgit** [comment]
* The IBM Security & Compliance scan results come back with an Excel spreadsheet with one sheet for summary results and another for detailed results. They don't look too much like OSCAL assessment results and will need mapping. I drafted json schema for each.
* I tested for both the detailed and summary results using **jsonschema** (installed with pip)

        % jsonschema -i sample_minimal_IBM_Cloud_security_and_compliance_scans_results_summary.json IBM_Cloud_security_and_compliance_scans_results_summary_schema.json
          % jsonschema -i sample_minimal_IBM_Cloud_security_and_compliance_scans_results_detailed.json IBM_Cloud_security_and_compliance_scans_results_detailed_schema.json

  Should return exit code of 0 if all is well, or complains about content otherwise.

* The above draft schemas and minimal samples are in the [schema-documents folder for branch enhancement/53](https://github.com/IBM/compliance-trestle/tree/enhancement/53/schema-documents).

* For OpenShift Compliance Operator results, in the definition for *arf:report-request*, the *content* element contains any XML in any non-ARF namespace, i.e., third party. A sample in [the Specification for ARF 1.1](https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7694.pdf) shows the XCCDF *benchmark* in the *arf:report-request* content.

**Comment by jeffdmgit** [comment]
Used trestle to generate a json schema for a custom observation, from OSCAL, but with two additional properties:

                "parameter-settings": {
                    "title": "Parameter-Settings",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/SetParameter"
                    }
                },
                "remediation-group": {
                    "title": "Remediation Group",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Remediation"
                    }
                }

Samples were created for XCCDF and OPA results, as well as SCC results, that use this modified schema definition.
