### ISSUE TITLE
Quotes are required when passing elements to split and merge commands

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#602]
Currently the elements specified by -e option in split and merge commands require that they be enclosed in quotes, specially if they have '*' as it gets expanded by the shell.

Need to come up with right usage on both Windows and Linux platforms to work in a seamless way. If quotes are mandatory then it should be clearly specified in documentation of these commands.

Also, any cleaning (removal of quotes) can happen in _validate_arguments method of CommandPlusDocs class. 

Required actions:
- [ ] Improve the documentation to explain this scenario
- [ ] Ensure that element paths are stripped of quotes.

**Comment by fsuits** [comment]
Just to be clear, I don't think quotes are needed for Windows as long as there is no whitespace separating two items in a command.  Normally the quotes will be passed in - and that will cause problems in windows.  A general solution - I think - is simply to strip any quotes from command line params that are passed in, and to have the docs suggest that quotes are needed in general.  For linux/mac the quotes are required, and for windows the quotes are optional - but if present need to be stripped in the trestle code.  In both cases stripping the quotes in code should work because for linux/mac they won't be there in the first place.
