### ISSUE TITLE
Replace legacy 'mock' functionality with pytest's monkeypatch.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#673]
## Issue description / feature objectives
Currently the trestle codebase for patching is primarily using functionality from the 'mock' library. Pytest provides functionality which is equivalent but cleaner using `monkeypatch` see: https://docs.pytest.org/en/latest/how-to/monkeypatch.html

This provides some substantial advantages - principally it avoids the 'with' argument that can be prone to being used incorrectly (scope can affect asserts used to test conditions).

## Completion criteria:
All use of mock patch are removed in favour of pytest intrinsic functionality.

**Comment by jeffdmgit** [comment]
Just to note that there is this pytest issue that includes some discussions with opinions for and against either pytest monkeypatch and unittest.mock.patch: https://github.com/pytest-dev/pytest/issues/4576

However just to clarify, the decision has been made to go with monkeypatch in pytest regardless.

**Comment by jeffdmgit** [comment]
On the [to_monkeypatch_jeff branch](https://github.com/IBM/compliance-trestle/tree/chore/to_monkeypatch_jeff), I tried this first with *remove_test.py*, and now this works. I did find an oddity where the error I raise in my mocked *execute()* is not detected with *pytest.raises()*, yet I find the log I specifically plant with *raise err.TrestleError()*, using the *caplog* fixture. It otherwise seems to work, with the assertion using the planted error log in the *caplog.text*.

I'll work through the other tests next.
