### ISSUE TITLE
As developer/user I would like to standardise return codes of the CLI commands

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#778]
## Issue description / feature objectives
At the moment the return codes for CLI commands are either 1-fail or 0-success. The task is to standardise the return codes and create a common structure that can be used across the project. Ideally, the codes returned by Trestle should be split into some logical parts providing user with information on what went wrong. The inspiration can be drawn from [POSIX](https://man7.org/linux/man-pages/man3/errno.3.html) error codes, [Bash](https://tldp.org/LDP/abs/html/exitcodes.html), or any other projects.

This change would also require to write a documentation for the return codes.

## Caveats / Assumptions
All CLI commands in Trestle return codes - this needs to be double checked that all existing commands return codes as per issue #203.

## Completion Criteria
1. Return codes are defined and all returns of 0 or 1 are replaced.
2. All commands return appropriate codes for the errors, success or warning.
3. Documentation is added

**Comment by butler54** [comment]
So my take on this would be (initially) codes for:

- Okay (0 by unix convention)
- Incorrect / missing args.
- Trestle unknown error.
- Validation / project setup failure in terms of files, most likely due to manual editing / malformed files
- IO error driven by OS level issues (permissions etc)
- Authentication error (for caching)


Not sure what others are on our list?
