### ISSUE TITLE
OscalBaseModel appears to be missing an equality operator.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#92]
**Describe the bug**
Equality operators are a minimum required comparitive operation. While I would have thought it was contained within core pydantic functionality it appears this is not the case.

**Comment by butler54** [comment]
So I had a check - it appears that within: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py __eq__ is defined for BaseModel. More Investigation is required here.

**Comment by leninmehedy** [comment]
FYI, I have a test_util method for now to relove this issue in the unit tests: https://github.com/IBM/compliance-trestle/blob/feature/split/tests/test_utils.py#L55

**Comment by leninmehedy** [comment]
That test_utils method will need to be updated once we find better way to do the equality check

**Comment by leninmehedy** [comment]
Just a quick update:
Equality operator `==` actually works as expected. I don't remember why it didn't work last time for me and made me override the `__eq__` method with JSON string comparison. 

Since the equality operator works expected, I have removed the custom equality check method to avoid confusion: https://github.com/IBM/compliance-trestle/commit/dffaf64eb0d3ec0c45141923a324c753461c51d8

**Comment by butler54** [comment]
Okay I'm closing this as a not fix then.
